spring:
    profiles:
        active:
            - dog
            - EN
            - prod
guru:
    username: YmlUserName
    password: YmlPassword
    jdbcurl: YmlUrl

---
spring:
    profiles: prod
guru:
    username: Yml_PROD_UserName
    password: Yml_Prod_Password
    jdbcurl: Yml_Prod_UrlForDb
